---
- name: Deploiement du Blog sur l'instance LocalStack
  hosts: blog_server
  become: yes
  tasks:
    - name: Mise a jour apt et installation Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: S'assurer que Docker est demarre
      service:
        name: docker
        state: started
        enabled: yes

    - name: Arreter les anciens conteneurs s'ils existent
      docker_container:
        name: "{{ item }}"
        state: absent
      loop: [ 'backend', 'frontend' ]

    - name: Lancer le Backend (Flask)
      docker_container:
        name: backend
        image: faso01/blog-backend:latest
        state: started
        restart_policy: always
        ports:
          - "5000:5000"

    - name: Lancer le Frontend (Nginx)
      docker_container:
        name: frontend
        image: faso01/blog-frontend:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
